#spring.datasource.url=jdbc:postgresql://localhost:5432/FinanceWallet
#spring.datasource.username=postgres
#spring.datasource.password=admin
#
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true

# Config do H2 Database
spring.datasource.url=jdbc:h2:mem:FinanceWallet
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin

# Config do JPA/Hibernate para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Habilita o console web do H2 para facilitar a visu
spring.h2.console.enabled=true

jwt.secret=MINHA_CHAVE_SECRETA_123
jwt.expiration=86400000